version: 2
updates:
- package-ecosystem: nuget
  directories:
    - "src/Pure.RelationalSchema.Self.Storage.Introjection"
    - "src/Tests/Pure.RelationalSchema.Self.Storage.Introjection.Tests"
  schedule:
    interval: daily
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
